project:
  type: website

website:
  title: "CID 02518535"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      
    right: 
      - icon: github
        href: https://github.com/olympia09
      - icon: envelope
        href: mailto:oi123@ic.ac.uk

      

format:
  html:
    theme: 
     light: cosmo
     dark: darkly
    css: styles.css
    toc: true

editor: visual

